name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
    - name: Chechout code
      uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASS }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: devkrolikowski/discordapp:latest
  deploy_on_vps:
    needs: publish_to_dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Reload discordapp service
        run: |-
          curl http://137.74.115.94:9000/hooks/redeploy-webhook
